export default [
  {
    position: { x: -1, y: 1, z: -1 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: true },
      { orange: true },
      { yellow: true },
    ],
  },
  {
    position: { x: -1, y: 0, z: -1 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: true },
      { orange: true },
      { yellow: false },
    ],
  },
  {
    position: { x: -1, y: -1, z: -1 },
    mask: [
      { white: true },
      { red: false },
      { green: false },
      { blue: true },
      { orange: true },
      { yellow: false },
    ],
  },
  {
    position: { x: -1, y: 1, z: 0 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: false },
      { orange: true },
      { yellow: true },
    ],
  },
  {
    position: { x: -1, y: 0, z: 0 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: false },
      { orange: true },
      { yellow: false },
    ],
  },
  {
    position: { x: -1, y: -1, z: 0 },
    mask: [
      { white: true },
      { red: false },
      { green: false },
      { blue: false },
      { orange: true },
      { yellow: false },
    ],
  },
  {
    position: { x: 0, y: 1, z: -1 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: true },
      { orange: false },
      { yellow: true },
    ],
  },
  {
    position: { x: 0, y: 0, z: -1 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: true },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 0, y: -1, z: -1 },
    mask: [
      { white: true },
      { red: false },
      { green: false },
      { blue: true },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 0, y: 1, z: 0 },
    mask: [
      { white: false },
      { red: false },
      { green: false },
      { blue: false },
      { orange: false },
      { yellow: true },
    ],
  },
  {
    position: { x: 0, y: -1, z: 0 },
    mask: [
      { white: true },
      { red: false },
      { green: false },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: -1, y: 1, z: 1 },
    mask: [
      { white: false },
      { red: false },
      { green: true },
      { blue: false },
      { orange: true },
      { yellow: true },
    ],
  },
  {
    position: { x: -1, y: 0, z: 1 },
    mask: [
      { white: false },
      { red: false },
      { green: true },
      { blue: false },
      { orange: true },
      { yellow: false },
    ],
  },
  {
    position: { x: -1, y: -1, z: 1 },
    mask: [
      { white: true },
      { red: false },
      { green: true },
      { blue: false },
      { orange: true },
      { yellow: false },
    ],
  },
  {
    position: { x: 1, y: 1, z: -1 },
    mask: [
      { white: false },
      { red: true },
      { green: false },
      { blue: true },
      { orange: false },
      { yellow: true },
    ],
  },
  {
    position: { x: 1, y: 0, z: -1 },
    mask: [
      { white: false },
      { red: true },
      { green: false },
      { blue: true },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 1, y: -1, z: -1 },
    mask: [
      { white: true },
      { red: true },
      { green: false },
      { blue: true },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 0, y: 1, z: 1 },
    mask: [
      { white: false },
      { red: false },
      { green: true },
      { blue: false },
      { orange: false },
      { yellow: true },
    ],
  },
  {
    position: { x: 0, y: 0, z: 1 },
    mask: [
      { white: false },
      { red: false },
      { green: true },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 0, y: -1, z: 1 },
    mask: [
      { white: true },
      { red: false },
      { green: true },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 1, y: 1, z: 0 },
    mask: [
      { white: false },
      { red: true },
      { green: false },
      { blue: false },
      { orange: false },
      { yellow: true },
    ],
  },
  {
    position: { x: 1, y: 0, z: 0 },
    mask: [
      { white: false },
      { red: true },
      { green: false },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 1, y: -1, z: 0 },
    mask: [
      { white: true },
      { red: true },
      { green: false },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 1, y: 1, z: 1 },
    mask: [
      { white: false },
      { red: true },
      { green: true },
      { blue: false },
      { orange: false },
      { yellow: true },
    ],
  },
  {
    position: { x: 1, y: 0, z: 1 },
    mask: [
      { white: false },
      { red: true },
      { green: true },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
  {
    position: { x: 1, y: -1, z: 1 },
    mask: [
      { white: true },
      { red: true },
      { green: true },
      { blue: false },
      { orange: false },
      { yellow: false },
    ],
  },
];
